server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #本地mysql
    url: jdbc:mysql://127.0.0.1:3306/bank?serverTimezone=GMT%2B8
    #mycat连接
    #url: jdbc:mysql://127.0.0.1:8066/bank
    username: root
    password: tycmysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect